### ISSUE TITLE
JQuery version

### ISSUE THREAD

**Issue by Kyrremann** [k-yak/stati18n#9]
I was wondering why you are not using the latest JQuery version, 2.1.3?

**Comment by k-yak** [comment]
It's fixed. I did some cleanup to the project too (remove useless files + alert in js). Thank you

**Comment by Kyrremann** [comment]
Cool.
I've started on a fork for parsing JSON that can be translated using http://www.getlocalization.com/. For now it's a bit quick and dirty, and just another python file, plus it does not support separate languages yet, but maybe later this weekend.

I've also changed a bit on your JS to allow for .css files with name different from stati18n.css.
